export enum StepsReviewApplication {
    STEP_1_PERSONAL_INFORMATION_APPLICANT = 1,
    STEP_2_APPLICATION_RECOGNITION = 2,
    STEP_3_PRODUCTION_BY_TYPE = 3,
    STEP_4_APPLICATON_RECOGNIZED = 4,
    STEP_5_DOCUMENTS = 5,
}